/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiscale_project1;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import static java.lang.Math.sqrt;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;



/**
 *
 * @author Michal
 */
public class Okno extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    JPanel jPanel1 = new JPanel();
    Rozrost rozrost;
    Rekrystalizacja rekrystal;
    int id=0;
    public Okno() {
        initComponents();
        rozrost = new Rozrost();
        rekrystal = null;
        this.bc1.setSelected(true);
        this.otocz_moora.setSelected(true);
        this.add(jPanel1);
        this.setSize(700, 500);
        jPanel1.setVisible(true);
        jPanel1.setLocation(15, 15);
        jPanel1.setSize(400, 400);
        jPanel1.setBackground(Color.black);
        jPanel1.addMouseListener(new MouseAdapter() 
                {
                @Override
                public void mousePressed(MouseEvent e) 
                {
                    System.out.println(e.getX()+" "+e.getY());
                    rozrost.dodajZarodek(e.getX(), e.getY(), id++);
                    rysuj();
                    jTextField1.setText(String.valueOf(Integer.valueOf(jTextField1.getText())-1));
                    
                    if (Integer.parseInt(jTextField1.getText())<=0)
                    {
                        jButton3.setEnabled(true);
                        jPanel1.removeMouseListener(this);
                    }
                }
                });
       
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        bc1 = new javax.swing.JRadioButton();
        bc2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        otocz_moora = new javax.swing.JRadioButton();
        otocz_neumana = new javax.swing.JRadioButton();
        otocz_hexp = new javax.swing.JRadioButton();
        otocz_penta = new javax.swing.JRadioButton();
        otocz_los = new javax.swing.JRadioButton();
        otocz_hexl = new javax.swing.JRadioButton();
        otocz_hexlos = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        promien = new javax.swing.JTextField();
        promien_zarodki = new javax.swing.JTextField();
        los2 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setSize(new java.awt.Dimension(668, 520));

        jButton1.setText("Start");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        bc1.setText("periodyczne");
        bc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bc1ActionPerformed(evt);
            }
        });

        bc2.setText("nie periodyczne");
        bc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bc2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Warunki brzegowe");

        jButton2.setText("Losowe");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("50");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setText("Wyklikaj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Równomierne");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Otoczenie");

        otocz_moora.setText("Moora");
        otocz_moora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otocz_mooraActionPerformed(evt);
            }
        });

        otocz_neumana.setText("von Neumana");
        otocz_neumana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otocz_neumanaActionPerformed(evt);
            }
        });

        otocz_hexp.setText("hexagonalne prawe");
        otocz_hexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otocz_hexpActionPerformed(evt);
            }
        });

        otocz_penta.setText("pentagonalne");
        otocz_penta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otocz_pentaActionPerformed(evt);
            }
        });

        otocz_los.setText("random CA z r=");
        otocz_los.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otocz_losActionPerformed(evt);
            }
        });

        otocz_hexl.setText("hexagonalne lewe");
        otocz_hexl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otocz_hexlActionPerformed(evt);
            }
        });

        otocz_hexlos.setText("hexagonalne losowe");
        otocz_hexlos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otocz_hexlosActionPerformed(evt);
            }
        });

        jButton5.setText("Z promieniem");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        promien.setText("10");
        promien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promienActionPerformed(evt);
            }
        });

        promien_zarodki.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        promien_zarodki.setText("20");
        promien_zarodki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promien_zarodkiActionPerformed(evt);
            }
        });

        los2.setText("losowe");
        los2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                los2ActionPerformed(evt);
            }
        });

        jButton6.setText("Rekrystal");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setText("min odl");

        jTextField2.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(425, 425, 425)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(promien_zarodki, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bc1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bc2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(otocz_moora)
                            .addComponent(otocz_neumana)
                            .addComponent(otocz_hexp)
                            .addComponent(otocz_hexl)
                            .addComponent(otocz_penta)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(otocz_los)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(promien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(los2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(otocz_hexlos))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(bc1)
                .addGap(0, 0, 0)
                .addComponent(bc2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6)
                            .addComponent(promien_zarodki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(1, 1, 1)
                            .addComponent(jButton3)
                            .addGap(21, 21, 21)
                            .addComponent(jButton4)
                            .addGap(6, 6, 6)
                            .addComponent(jButton5)))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otocz_moora)
                    .addComponent(jButton6))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(otocz_neumana)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(otocz_hexp)
                .addGap(0, 0, 0)
                .addComponent(otocz_hexl)
                .addGap(0, 0, 0)
                .addComponent(otocz_hexlos)
                .addGap(0, 0, 0)
                .addComponent(otocz_penta)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otocz_los))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(los2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
  
    
    
    public void rysuj()
    {
        Graphics g = jPanel1.getGraphics();
        g.clearRect(0,0,400,400);
        for(int i=0; i<400; i++)
        {
           for(int j=0; j<400; j++)
           {
               if (rozrost.tab[i][j] >0)
               {
                   g.setColor(Color.getHSBColor(rozrost.tab[i][j]*20%255+1,rozrost.tab[i][j]%255*50+1,rozrost.tab[i][j]%255*37+1));
                   g.fillRect(i,j,1,1);
               }
               else
               {
                   g.setColor(Color.black);
                   g.fillRect(i,j,1,1);
               }
               
           }
        }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Boolean bc=false;
        if (this.bc1.isSelected())  bc=true;//periodyczne
        else if (this.bc2.isSelected()) bc=false;  //nieperiodyczne
        
        while(!rozrost.koniec) {
        if (this.otocz_moora.isSelected())rozrost.moor(bc,0); 
        else if (this.otocz_neumana.isSelected()) rozrost.neuman(bc);
        else if (this.otocz_hexp.isSelected()) rozrost.hexagp(bc);
        else if (this.otocz_hexl.isSelected()) rozrost.hexagl(bc);
        else if (this.otocz_hexlos.isSelected()) rozrost.hexaglos(bc);
        else if (this.otocz_penta.isSelected()) rozrost.penta(bc);
        else if (this.los2.isSelected()) rozrost.los2(bc);
        else if (this.otocz_los.isSelected()) rozrost.los(bc, Integer.parseInt(promien.getText()));
        
       
        
        rysuj();
        }
        rozrost.koniec=false;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bc2ActionPerformed
        this.bc1.setSelected(false);
        if (!bc1.isSelected()) this.bc2.setSelected(true);
    }//GEN-LAST:event_bc2ActionPerformed

    private void bc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bc1ActionPerformed
        this.bc2.setSelected(false);
        if (!bc2.isSelected()) this.bc1.setSelected(true);
    }//GEN-LAST:event_bc1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Random r;
        int x,y;
        int id=1;
        rozrost.wyczysc();
        for(int i=0; i<Integer.parseInt(jTextField1.getText()); i++)
        {
            r=new Random();
            x=r.nextInt(400);
            y=r.nextInt(400);
            rozrost.dodajZarodek(x, y, id++);
        }
        rysuj();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton3.setEnabled(false);
        rozrost.wyczysc();
        rysuj();
        id=0;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int id=1;
        rozrost.wyczysc();
        int co_ile=400/(int)sqrt(Integer.parseInt(jTextField1.getText()));
        System.out.println(co_ile);
        for(int i=0; i<400; i+=co_ile)
        {
            for(int j=0; j<400; j+=co_ile)
            {
                rozrost.dodajZarodek(i, j, id++);
            }
        }
        rysuj();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void otocz_mooraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otocz_mooraActionPerformed
        this.otocz_moora.setSelected(true);
        this.otocz_neumana.setSelected(false);
        this.otocz_hexp.setSelected(false);
        this.otocz_hexl.setSelected(false);
        this.otocz_hexlos.setSelected(false);
        this.otocz_penta.setSelected(false);
        this.otocz_los.setSelected(false);
        this.los2.setSelected(false);
    }//GEN-LAST:event_otocz_mooraActionPerformed

    private void otocz_neumanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otocz_neumanaActionPerformed
        this.otocz_moora.setSelected(false);
        this.otocz_neumana.setSelected(true);
        this.otocz_hexp.setSelected(false);
        this.otocz_hexl.setSelected(false);
        this.otocz_hexlos.setSelected(false);
        this.otocz_penta.setSelected(false);
        this.otocz_los.setSelected(false);
        this.los2.setSelected(false);
    }//GEN-LAST:event_otocz_neumanaActionPerformed

    private void otocz_hexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otocz_hexpActionPerformed
        this.otocz_moora.setSelected(false);
        this.otocz_neumana.setSelected(false);
        this.otocz_hexp.setSelected(true);
        this.otocz_hexl.setSelected(false);
        this.otocz_hexlos.setSelected(false);
        this.otocz_penta.setSelected(false);
        this.otocz_los.setSelected(false);
        this.los2.setSelected(false);
    }//GEN-LAST:event_otocz_hexpActionPerformed

    private void otocz_pentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otocz_pentaActionPerformed
        this.otocz_moora.setSelected(false);
        this.otocz_neumana.setSelected(false);
        this.otocz_hexp.setSelected(false);
        this.otocz_hexl.setSelected(false);
        this.otocz_hexlos.setSelected(false);
        this.otocz_penta.setSelected(true);
        this.otocz_los.setSelected(false);
        this.los2.setSelected(false);
    }//GEN-LAST:event_otocz_pentaActionPerformed

    private void otocz_losActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otocz_losActionPerformed
        this.otocz_moora.setSelected(false);
        this.otocz_neumana.setSelected(false);
        this.otocz_hexp.setSelected(false);
        this.otocz_hexl.setSelected(false);
        this.otocz_hexlos.setSelected(false);
        this.otocz_penta.setSelected(false);
        this.otocz_los.setSelected(true);
        this.los2.setSelected(false);
    }//GEN-LAST:event_otocz_losActionPerformed

    private void otocz_hexlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otocz_hexlActionPerformed
        this.otocz_moora.setSelected(false);
        this.otocz_neumana.setSelected(false);
        this.otocz_hexp.setSelected(false);
        this.otocz_hexl.setSelected(true);
        this.otocz_hexlos.setSelected(false);
        this.otocz_penta.setSelected(false);
        this.otocz_los.setSelected(false);
        this.los2.setSelected(false);
    }//GEN-LAST:event_otocz_hexlActionPerformed

    private void otocz_hexlosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otocz_hexlosActionPerformed
        this.otocz_moora.setSelected(false);
        this.otocz_neumana.setSelected(false);
        this.otocz_hexp.setSelected(false);
        this.otocz_hexl.setSelected(false);
        this.otocz_hexlos.setSelected(true);
        this.otocz_penta.setSelected(false);
        this.otocz_los.setSelected(false);
        this.los2.setSelected(false);
    }//GEN-LAST:event_otocz_hexlosActionPerformed

    private void promienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promienActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int pr=Integer.parseInt(promien_zarodki.getText());
        Random r = null;
        int x=0,y=0;
        int id=1;
        rozrost.wyczysc();
        boolean ok=false;
        
        for(int i=0; i<Integer.parseInt(jTextField1.getText()); i++)
        {
            ok = false;
            while(!ok)
            {
                r=new Random();
                x=r.nextInt(400);
                y=r.nextInt(400);
                ok = true;
                for(int a=-pr; a<pr*2;a++)
                {
                    for(int b=-pr; b<pr*2;b++)
                    {
                        if (sqrt((a-x)^2+(b-y)^2) > pr) ok=false;
                        else if ((x+a)<0 || (y+b)<0 || (x+a)>399 || (y+b)>399) ok=false;
                        else if (rozrost.tab[x+a][y+b] > 0)ok=false;
                    }
                }
            }
            if (ok) {
                rozrost.dodajZarodek(x, y, id++);
            }
            System.out.println(x + " " + y);

        }
        rysuj();


    }//GEN-LAST:event_jButton5ActionPerformed

    private void promien_zarodkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promien_zarodkiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_promien_zarodkiActionPerformed

    private void los2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_los2ActionPerformed
        this.otocz_moora.setSelected(false);
        this.otocz_neumana.setSelected(false);
        this.otocz_hexp.setSelected(false);
        this.otocz_hexl.setSelected(false);
        this.otocz_hexlos.setSelected(false);
        this.otocz_penta.setSelected(false);
        this.otocz_los.setSelected(false);
        this.los2.setSelected(true);
    }//GEN-LAST:event_los2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Boolean bc = false;
        if (this.bc1.isSelected()) {
            bc = true;//periodyczne
        } else if (this.bc2.isSelected()) {
            bc = false;  //nieperiodyczne
        }
        
        int jakie = 0;
        if (this.otocz_moora.isSelected()) jakie = 0;
            else if (this.otocz_neumana.isSelected()) jakie = 1;
            else if (this.otocz_hexp.isSelected()) jakie = 2;
            else if (this.otocz_hexl.isSelected()) jakie = 3;
            else if (this.otocz_hexlos.isSelected()) jakie = 4;
            else if (this.otocz_penta.isSelected()) jakie = 5;
            else if (this.los2.isSelected()) jakie = 6;
            else if (this.otocz_los.isSelected()) jakie = 7;
        
        rekrystal = new Rekrystalizacja(this.rozrost, Integer.parseInt(jTextField1.getText()));
        rekrystal.znajdz_granice();

        Graphics g = jPanel1.getGraphics();
        g.clearRect(0, 0, 400, 400);
        for (int i = 0; i < 400; i++) {
            for (int j = 0; j < 400; j++) {
                if (rozrost.tab[i][j] > 0) {
                    g.setColor(Color.getHSBColor(rozrost.tab[i][j] * 20 % 255 + 1, rozrost.tab[i][j] % 255 * 50 + 1, rozrost.tab[i][j] % 255 * 37 + 1));
                    g.fillRect(i, j, 1, 1);
                } else {
                    g.setColor(Color.black);
                    g.fillRect(i, j, 1, 1);
                }
                if (rekrystal.granice[i][j]) {
                    g.setColor(Color.black);
                    g.fillRect(i, j, 1, 1);
                }

            }
        }

        try {
            Thread.sleep(200);
        } catch (InterruptedException ex) {
            Logger.getLogger(Okno.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        rekrystal.koniec=false;
        int odl=Integer.parseInt(jTextField2.getText());
        int ile=500000;
       
        while (!rekrystal.koniec) {
            

            rekrystal.rekrystalizuj(bc, jakie, odl, ile);

            

           // g = jPanel1.getGraphics();
           // g.clearRect(0, 0, 400, 400);
            for (int i = 0; i < 400; i++) {
                for (int j = 0; j < 400; j++) {
                    if (rekrystal.zrek.tab[i][j] >0) {
                        g.setColor(Color.getHSBColor(rekrystal.zrek.tab[i][j] * 3 % 255 + 1, rekrystal.zrek.tab[i][j] % 255 * 5 + 1, rekrystal.zrek.tab[i][j] % 255 * 7 + 1));
                        g.fillRect(i, j, 1, 1);

                    }
                }
            }
            
        }
       // rozrost.koniec = false;

    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bc1;
    private javax.swing.JRadioButton bc2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton los2;
    private javax.swing.JRadioButton otocz_hexl;
    private javax.swing.JRadioButton otocz_hexlos;
    private javax.swing.JRadioButton otocz_hexp;
    private javax.swing.JRadioButton otocz_los;
    private javax.swing.JRadioButton otocz_moora;
    private javax.swing.JRadioButton otocz_neumana;
    private javax.swing.JRadioButton otocz_penta;
    private javax.swing.JTextField promien;
    private javax.swing.JTextField promien_zarodki;
    // End of variables declaration//GEN-END:variables
}
